import esbuild from "esbuild";
import process from "process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit https://github.com/tnichols217/bioBarcodesTS
*/
`;

const PROD = "production"
const WATCH = "watch"

const args = process.argv.slice(2)

const prod = args.includes(PROD)
const watch = args.includes(WATCH)

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['out/build/main.js'],
	bundle: true,
	format: 'cjs',
	watch: watch,
    minify: prod,
    platform: 'node',
	target: 'esnext',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outdir: 'out/bundle',
}).catch(() => process.exit(1));
