name: Docker builder

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Get nix
        run: |
          sudo mkdir /nix
          sudo sh <(curl -L https://nixos.org/nix/install) --no-daemon

      - name: Run a one-line script
        run: sudo nix build $GITHUB_WORKSPACE#docker
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: docker.img
          path: $GITHUB_WORKSPACE/result
