name: Docker builder

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get nix
        uses: cachix/install-nix-action@v17

      - name: Build the Docker image
        run: nix build $GITHUB_WORKSPACE#docker

      - name: For testing purposes
        run: |
          cd $GITHUB_WORKSPACE
          ls -al
        
      - name: Upload the image
        uses: actions/upload-artifact@v3.1.0
        with:
          name: docker.img
          path: $GITHUB_WORKSPACE/result
